apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: file-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: file-server
    spec:
      containers:
        - name: file-server
          image: ghcr.io/zoomoid/go-autoindex:0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: files
              mountPath: /var/www
      volumes: []
