apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: file-server
  labels:
    app.kubernetes.io/name: file-server
spec:
  rules:
    - host: files.zoomoid.de
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: file-server
                port:
                  name: http
